"""Associate distensibility ablation metrics with tile location.

Uses the ablation_summary.csv generated by distensibility_ablation.py
and tile_positions_manual.json from the analysis config.  The default
"heart" anchor is the graph's _av_ref_art_tile when present, otherwise
the reference tile, otherwise the mosaic center.  A second anchor uses
the centroid of source boundary nodes.
"""
from __future__ import annotations

import argparse
import csv
import json
import math
import pickle
from pathlib import Path
from typing import Dict, Optional

import numpy as np

TILE_RAW_HEIGHT = 704
TILE_RAW_WIDTH = 640


def _read_config(path: Optional[str]) -> tuple[dict, Optional[Path]]:
    if not path:
        return {}, None
    p = Path(path).resolve()
    with open(p) as f:
        return json.load(f), p.parent


def _resolve(cli_val: Optional[str], cfg: dict, cfg_dir: Optional[Path],
             key: str) -> Optional[Path]:
    val = cli_val if cli_val is not None else cfg.get(key)
    if val is None:
        return None
    p = Path(val)
    if p.is_absolute() or cfg_dir is None:
        return p
    return (cfg_dir / p).resolve()


def _float_or_nan(v):
    try:
        return float(v)
    except Exception:
        return float("nan")


def _rankdata(x):
    x = np.asarray(x, dtype=float)
    order = np.argsort(x)
    ranks = np.empty_like(x)
    i = 0
    while i < len(x):
        j = i + 1
        while j < len(x) and x[order[j]] == x[order[i]]:
            j += 1
        ranks[order[i:j]] = 0.5 * (i + j - 1)
        i = j
    return ranks


def _corr(x, y, spearman=False):
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    ok = np.isfinite(x) & np.isfinite(y)
    if ok.sum() < 3:
        return float("nan")
    xx = _rankdata(x[ok]) if spearman else x[ok]
    yy = _rankdata(y[ok]) if spearman else y[ok]
    if np.std(xx) == 0 or np.std(yy) == 0:
        return float("nan")
    return float(np.corrcoef(xx, yy)[0, 1])


def _tile_centers(tile_positions: Path, mosaic_height: float) -> Dict[int, dict]:
    with open(tile_positions) as f:
        data = json.load(f)
    tiles = data["tiles"]
    min_y = min(float(t["translate_y"]) for t in tiles.values())
    min_x = min(float(t["translate_x"]) for t in tiles.values())
    out = {}
    for key, t in tiles.items():
        tid = int(key)
        sy = float(t.get("scale_y", 1.0))
        sx = float(t.get("scale_x", 1.0))
        row = float(t["translate_y"]) - min_y + 0.5 * TILE_RAW_HEIGHT * sy
        col = float(t["translate_x"]) - min_x + 0.5 * TILE_RAW_WIDTH * sx
        out[tid] = {
            "tile_id": tid,
            "display_row": row,
            "display_col": col,
            "graph_x": col,
            "graph_y": float(mosaic_height) - row,
        }
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default=None)
    ap.add_argument("--graph", default=None)
    ap.add_argument("--tile-positions", default=None)
    ap.add_argument("--summary", default=None,
                    help="ablation_summary.csv. Defaults to renders/meeting/"
                         "distensibility_ablation/ablation_summary.csv")
    ap.add_argument("--ablation", default="h1_free_boundary",
                    help="Ablation row to analyze.")
    ap.add_argument("--out-dir", default=None)
    args = ap.parse_args()

    cfg, cfg_dir = _read_config(args.config)
    graph_path = _resolve(args.graph, cfg, cfg_dir, "mosaic_graph")
    tile_pos_path = _resolve(args.tile_positions, cfg, cfg_dir,
                             "tile_positions")
    if graph_path is None or tile_pos_path is None:
        raise SystemExit("Need --config or both --graph and --tile-positions.")
    project_root = Path(__file__).resolve().parent.parent
    summary_path = (Path(args.summary).resolve() if args.summary else
                    project_root / "renders" / "meeting"
                    / "distensibility_ablation" / "ablation_summary.csv")
    out_dir = (Path(args.out_dir).resolve() if args.out_dir else
               summary_path.parent / "location_analysis")
    out_dir.mkdir(parents=True, exist_ok=True)

    with open(graph_path, "rb") as f:
        graph = pickle.load(f)
    H = float(graph.graph.get("mosaic_height", TILE_RAW_HEIGHT))
    centers = _tile_centers(tile_pos_path, H)

    # Heart/reference anchor.
    heart_tile = graph.graph.get("_av_ref_art_tile") \
        or graph.graph.get("reference_vid")
    if heart_tile is None:
        try:
            with open(tile_pos_path) as f:
                heart_tile = json.load(f).get("reference_vid")
        except Exception:
            heart_tile = None
    heart_anchor = None
    if heart_tile is not None and int(heart_tile) in centers:
        c = centers[int(heart_tile)]
        heart_anchor = (c["graph_x"], c["graph_y"])
    else:
        xs = [c["graph_x"] for c in centers.values()]
        ys = [c["graph_y"] for c in centers.values()]
        heart_anchor = (float(np.mean(xs)), float(np.mean(ys)))

    # Boundary source centroid anchor.
    src_xy = []
    for _n, d in graph.nodes(data=True):
        if d.get("boundary_type") == "source":
            try:
                src_xy.append((float(d["x"]), float(d["y"])))
            except Exception:
                pass
    source_anchor = (float(np.mean([p[0] for p in src_xy])),
                     float(np.mean([p[1] for p in src_xy]))) if src_xy else heart_anchor

    rows = []
    with open(summary_path) as f:
        for r in csv.DictReader(f):
            if r.get("ablation") != args.ablation:
                continue
            tid = int(r["tile_id"])
            if tid not in centers:
                continue
            c = centers[tid]
            dxh = c["graph_x"] - heart_anchor[0]
            dyh = c["graph_y"] - heart_anchor[1]
            dxs = c["graph_x"] - source_anchor[0]
            dys = c["graph_y"] - source_anchor[1]
            row = dict(r)
            row.update(c)
            row["dist_heart_tile_px"] = math.hypot(dxh, dyh)
            row["dist_source_centroid_px"] = math.hypot(dxs, dys)
            row["log10_D_hat"] = math.log10(_float_or_nan(r["D_hat"])) \
                if _float_or_nan(r["D_hat"]) > 0 else float("nan")
            for k in ("chi2_red", "width_decades_dchi1",
                      "width_decades_dchi384", "max_delta_chi2",
                      "n_obs", "n_h1", "n_h2"):
                row[k] = _float_or_nan(r.get(k))
            rows.append(row)

    loc_csv = out_dir / f"{args.ablation}_location_metrics.csv"
    fieldnames = sorted({k for r in rows for k in r})
    with open(loc_csv, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(rows)

    # Correlations.
    metrics = ["log10_D_hat", "width_decades_dchi1",
               "width_decades_dchi384", "chi2_red", "max_delta_chi2"]
    distances = ["dist_heart_tile_px", "dist_source_centroid_px",
                 "graph_x", "graph_y"]
    corr_csv = out_dir / f"{args.ablation}_correlations.csv"
    with open(corr_csv, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=[
            "ablation", "x", "y", "pearson_r", "spearman_r", "n"])
        w.writeheader()
        for xname in distances:
            x = [_float_or_nan(r[xname]) for r in rows]
            for yname in metrics:
                y = [_float_or_nan(r[yname]) for r in rows]
                ok = np.isfinite(x) & np.isfinite(y)
                w.writerow(dict(
                    ablation=args.ablation, x=xname, y=yname,
                    pearson_r=_corr(x, y, False),
                    spearman_r=_corr(x, y, True),
                    n=int(ok.sum())))

    # Plots.
    import matplotlib.pyplot as plt

    x = np.array([r["dist_heart_tile_px"] for r in rows], dtype=float)
    yD = np.array([r["log10_D_hat"] for r in rows], dtype=float)
    yw = np.array([r["width_decades_dchi1"] for r in rows], dtype=float)
    yc = np.array([r["chi2_red"] for r in rows], dtype=float)
    tiles = [int(r["tile_id"]) for r in rows]

    fig, axs = plt.subplots(1, 3, figsize=(15, 4.4))
    for ax, y, label in [
        (axs[0], yD, "log10(D_hat)"),
        (axs[1], yw, "Delta chi2 <= 1 width (decades)"),
        (axs[2], yc, "chi2_red"),
    ]:
        ax.scatter(x, y, s=55, c="#4C78A8", edgecolor="white", lw=0.7)
        for tid, xi, yi in zip(tiles, x, y):
            if np.isfinite(yi):
                ax.text(xi, yi, f" {tid}", fontsize=8, va="center")
        ax.set_xlabel("distance from heart/reference tile (px)")
        ax.set_ylabel(label)
        ax.grid(alpha=0.25)
    axs[2].set_yscale("log")
    fig.suptitle(f"Location association: {args.ablation}")
    fig.tight_layout()
    scatter_png = out_dir / f"{args.ablation}_distance_scatter.png"
    fig.savefig(scatter_png, dpi=180)
    plt.close(fig)

    fig, axs = plt.subplots(1, 3, figsize=(15, 4.6))
    map_specs = [
        ("log10_D_hat", "log10(D_hat)", "viridis"),
        ("width_decades_dchi1", "uncertainty width", "magma"),
        ("chi2_red", "chi2_red", "plasma"),
    ]
    for ax, (key, title, cmap) in zip(axs, map_specs):
        vals = np.array([_float_or_nan(r[key]) for r in rows])
        if key == "chi2_red":
            vals = np.log10(np.maximum(vals, 1e-6))
            title = "log10(chi2_red)"
        sc = ax.scatter([r["graph_x"] for r in rows],
                        [r["graph_y"] for r in rows],
                        c=vals, cmap=cmap, s=95,
                        edgecolor="white", lw=0.7)
        ax.scatter([heart_anchor[0]], [heart_anchor[1]], marker="*",
                   s=190, color="cyan", edgecolor="black", label="heart tile")
        ax.scatter([source_anchor[0]], [source_anchor[1]], marker="P",
                   s=130, color="red", edgecolor="black", label="source centroid")
        for r in rows:
            ax.text(r["graph_x"], r["graph_y"], f" {int(r['tile_id'])}",
                    fontsize=8, va="center")
        ax.set_aspect("equal", adjustable="box")
        ax.set_title(title)
        ax.set_xlabel("mosaic x (px)")
        ax.set_ylabel("mosaic y (px)")
        ax.grid(alpha=0.2)
        plt.colorbar(sc, ax=ax, shrink=0.8)
    axs[0].legend(fontsize=7)
    fig.tight_layout()
    map_png = out_dir / f"{args.ablation}_spatial_map.png"
    fig.savefig(map_png, dpi=180)
    plt.close(fig)

    print(f"Wrote {loc_csv}")
    print(f"Wrote {corr_csv}")
    print(f"Wrote {scatter_png}")
    print(f"Wrote {map_png}")
    print(f"heart/reference anchor: {heart_anchor}")
    print(f"source centroid anchor: {source_anchor}")


if __name__ == "__main__":
    main()
